---
title: "Final class"
format: 
  revealjs:
    smaller: true
    scrollable: true
    echo: true
---

## We did it!

You are now comfortable with our code from Week 1!

[Final exercise plotting gallery](https://docs.google.com/document/d/1igje3fWfyadVKRGPmH4ZhObZKCtMqyeyVdU4knSrUnk/edit?tab=t.0#heading=h.ycaeyqy8a6rq)

[Intro to R Cheatsheet](https://hutchdatascience.org/Intro_to_R/cheatsheet.html)

## Certification/Badging

Certification upon completing 4 out of the 5 assignments: <https://www.credly.com/org/fred-hutch/badge/intro-to-r>

What it is:

-   A display of what you accomplished in the course, shareable in your professional networks such as LinkedIn, similar to online education services such as Coursera.

What it isn't:

-   Accreditation through an university or degree-granting program.

I've been keeping track of folks' completion, will share shortly.

## Continuing your education

-   [Intermediate R](https://hutchdatascience.org/Intermediate_R/) (to be taught live in Winter 2027)

. . .

-   Reference texts:

    -   [Hands-on Programming with R, by Garrett Grolemund](https://rstudio-education.github.io/hopr/)

    -   [R for Data Science, by Hadley Wickham](https://r4ds.hadley.nz/)

## Connecting to rest of DaSL/OCDO

-   [Data House Calls](https://ocdo.fredhutch.org/programs/dhc.html)

-   [Fred Hutch Data Slack](https://join.slack.com/t/fhdata/signup)

-   [Fred Hutch SciWiki](https://ocdo.fredhutch.org/programs/sciwiki.html)

-   [Open source software at Fred Hutch: WILDS](https://getwilds.org/)

## Please fill out survey!

Our [class survey](https://forms.gle/Saq4omUj61XL4fuq6) makes a huge difference for us.

## Working on your own projects

-   Download and install [R](https://cloud.r-project.org/)

-   Download and install [RStudio](https://posit.co/downloads/)

## Getting started in RStudio

-   `File -> New Project`

-   This is similar to a Posit Cloud workspace:

    -   Any library you install in this workspace will be only for this Project

    -   Create new Quarto Document or R Script to run your analysis

    -   Highly recommend to put your data in the project folder, so you can access it in a relative path.

. . .

-   Install and load relevant packages

    -   `install.packages("tidyverse")`

    -   `library(tidyverse)`

## Loading your own data in

CSV file [example](https://pos.it/r4ds-students-csv):

```         
Student ID,Full Name,favourite.food,mealPlan,AGE
1,Sunil Huffmann,Strawberry yoghurt,Lunch only,4
2,Barclay Lynn,French fries,Lunch only,5
3,Jayendra Lyne,N/A,Breakfast and lunch,7
4,Leon Rossini,Anchovies,Lunch only,
5,Chidiegwu Dunkel,Pizza,Breakfast and lunch,five
6,Güvenç Attila,Ice cream,Lunch only,6
```

Feel free to download this example file and place it in your project directory.

. . .

```{r}
library(tidyverse)
students = read_csv("https://raw.githubusercontent.com/hadley/r4ds/main/data/students.csv")
students
```

. . .

Some more information about [filepaths here](https://clinic.ds.uchicago.edu/tutorials/filepaths.html), and [here](https://www.redhat.com/en/blog/linux-path-absolute-relative).

## Other file formats

`read_tsv("file.tsv")` for tab-deliminated files

`read_excel("example.xlsx")` for excel files

`read_excel("example.xlsx", sheet = "chickwts")` for excel files with a sheet name

`read_delim()` for general-deliminated files, such as:

`read_delim("file.csv", sep = ",")`

## Writing out data

`write_csv(my_dataframe, "filepath.csv")`

`write_excel(my_dataframe, "filepath.xlsx")`

`write_delim(my_dataframe, "filepath.tsv", sep="\t")`

## Looking up documentation

-   Use the `?` operation: `?read_delim`

-   Package documentation: <https://readr.tidyverse.org/index.html>

    -   Function documentation: <https://readr.tidyverse.org/reference/read_delim.html>

-   Vetted online resources:

    -   Stackoverflow: <https://stackoverflow.com/collectives/r-language>

## Saving plots

```         
pdf("myplot.pdf", width=8, height=4)
ggplot(s)
dev.off()
```

## Project and spreadsheet organization

Consider having subfolders for:

-   Raw data and metadata

-   Analyzed data

-   Plots

[Good enough practices for scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)
